### ISSUE TITLE
[FEATURE]: Better MoreHUD SE integration

### ISSUE THREAD

**Issue by artemyv** [MissCorruption/QuickLootIE#93]
### Feature Title

Better MoreHUD SE integration

### Motivation

If container contains Armor or weapon similar to what I'm using but potentially better, I need always get into full container mode to decide if I need to take them. 

### Feature Description

The MoreHUD SE mod (https://www.nexusmods.com/skyrimspecialedition/mods/12688) has following features:

- Current Weapon Damage and Difference (Only when targeting a weapon)
- Current Armor Rating and Difference (Only when targeting armor)

Unfortunately, they do not work when item is selected in QuickLoot interface.

Is it possible to make it work from QuickLoot window? Currently I need always get into full container mode to select what I need to take. Or take all and then drop what I do not need.

Not for me personally - but others may be interested in following features of MoreHUD as well
- Known Ingredient Effects (Only when targeting ingredients or flora)
- The number of the targeted items that the player already has in his/her inventory (Only when targeting something that can be picked up or harvested and when the item exists in the inventory)

### Additional Context

![Image](https://github.com/user-attachments/assets/0fbadc24-833b-45a0-a443-4fe6231fc9df) - full interface

![Image](https://github.com/user-attachments/assets/19a04728-e768-40d9-a650-5532644b23a2) - Quick loot interface

**Comment by artemyv** [comment]
![Image](https://github.com/user-attachments/assets/f55f6a63-9a0d-45ec-a0f3-aa2f0692e29a) When Item is selected outside of container - This is 2nd possibility when feature works - so maybe Quickloot can inject its data like this and not like the full container mode

**Comment by AtomCrafty** [comment]
I'm not aware of a way for us to trigger the moreHUD overlay from within QuickLoot.

The moreHUD devs could in theory do this on their end by listening to our item selection events, but I strongly assume they would consider this out of scope for moreHUD.

I think the closest we'll get to what you want is the "custom data providers" feature I've been thinking about for a while. If we decide to implement it it would allow third party plugins to display text in the blank space next to the weight info underneath the item list.

**Comment by artemyv** [comment]
I suspected that MoreHUD is subscribed to some event like "ItemHovered" and their dll SSE plugin is handling it and throws event for swf to display info

So I was hoping QuickLoot UI can generate same "ItemHovered" event when Item is selected in its UI...

I'm not familiar with game mechanics to verify my hypothesis.
I would not know where to start to trace events generated by regular "mouse over" and by QuickLoot Selection

Could you point me to some docs/howtos I can read about it?

**Comment by AtomCrafty** [comment]
As far as I'm aware moreHUD does not expose a public API, and I do not want to include code in QLIE that messes with the internals of other mods. If anything that would need to be done by a third party SKSE plugin that receives the selection events through our API and then calls functions within moreHUD to coerce it into displaying the info you want. If you'd like to look into creating that, be my guest.

For the "item hovered" event you're thinking of SKSE provides an event called `CrosshairRefEvent`. If I were to start investigating I'd take a look at [moreHUD's CrosshairRefEvent handler](https://github.com/ahzaab/moreHUDSE/blob/master/src/Events.cpp#L109-L113) first and follow the logic from there. Your issue is going to be that crosshair events always provide a `TESObjectREFR`, i.e. an object reference that exists in the game's worldspace. Items in inventories like the ones listed by QuickLoot do not exist as actual object references, so you have nothing to even pass to that event handler.

**Comment by AtomCrafty** [comment]
I don't really see the need for an elaborate setup. The idea behind the header file is that you simply copy it to your own repository and adjust it to your needs. If you have a look at our [integrations folder](https://github.com/MissCorruption/QuickLootIE/tree/main/src/Integrations) you'll see that we have modified versions of the Completionist and BTPS API headers in there. We've adjusted them to fit our namespace schema.

**Comment by artemyv** [comment]
Thank you for suggestion
It works fine with headers from 3.4.1
But when adding headers from trunk (API V2) - I got errors due to Windows API function calls
```
src\integration\QuickLootIE\V2/QuickLootAPI.h(105): error C3861: 'GetModuleHandleA': identifier not found
src\integration\QuickLootIE\V2/QuickLootAPI.h(106): error C3861: 'GetProcAddress': identifier not found
src\integration\QuickLootIE\V2/QuickLootAPI.h(110): error C2064: term does not evaluate to a function taking 0 arguments
```
Should I include windows .h before your header, or you can make your header self-contained?
I have updated example code in my repo.

**Comment by AtomCrafty** [comment]
Either approach works. Tbh I just didn't notice it wasn't included in the header because Windows.h is included by QLIE anyway. But also I think it should be left to the plugin author when and how to include Windows.h (or not at all in your case) since it is a huge header and can break things when included at the wrong time or without setting up the right preprocessor symbols first.
